import { create } from "zustand";

const useWeeklyMealStore = create(() => ({
    weeklyMeals: [
        {
            id: 1,
            mealName: "Grilled Chicken Salad",
            description: "Fresh greens with grilled chicken and vinaigrette.",
            calories: 350,
            dairyFree: true,
            nutsFree: true,
            glutenFree: true,
            deliveryType: "Hot Meal",
            image: "https://www.afarmgirlsdabbles.com/wp-content/uploads/2022/09/Southwest-Salad38461_1400.jpg",
        },
        {
            id: 2,
            mealName: "Vegan Buddha Bowl",
            description: "Quinoa, roasted veggies, and tahini dressing.",
            calories: 420,
            dairyFree: true,
            nutsFree: true,
            glutenFree: true,
            deliveryType: "Frozen Meal",
            image: "https://elavegan.com/wp-content/uploads/2021/05/vegan-buddha-bowl-with-chickpeas-avocado-colorful-veggies-and-green-dressing-on-the-side.jpg",
        },
        {
            id: 3,
            mealName: "Spaghetti Bolognese",
            description: "Spaghetti with a hearty meat sauce.",
            calories: 600,
            dairyFree: false,
            nutsFree: true,
            glutenFree: false,
            deliveryType: "Hot Meal",
            image: "https://www.ericlyons.co.uk/wp-content/uploads/2021/06/8K0A7866.jpg",
        },
        {
            id: 4,
            mealName: "Beef Stir-fry",
            description: "Beef with vegetables in a savory sauce.",
            calories: 500,
            dairyFree: true,
            nutsFree: true,
            glutenFree: true,
            deliveryType: "Frozen Meal",
            image: "https://www.allrecipes.com/thmb/7N-Xq1XMMJw8G0KJv2e0ETUYB2I=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/228823-quick-beef-stir-fry-DDMFS-4x3-1f79b031d3134f02ac27d79e967dfef5.jpg",
        },
        {
            id: 5,
            mealName: "Tofu Pad Thai",
            description: "Rice noodles, tofu, and tangy sauce.",
            calories: 450,
            dairyFree: true,
            nutsFree: false,
            glutenFree: true,
            deliveryType: "Hot Meal",
            image: "https://plantbasedonabudget.com/wp-content/uploads/2013/03/Pad-Thai-Inspired-Stir-Fry-Plant-Based-on-a-Budget-1.jpg",
        },
        {
            id: 6,
            mealName: "Chicken Alfredo",
            description: "Creamy pasta with grilled chicken.",
            calories: 650,
            dairyFree: false,
            nutsFree: true,
            glutenFree: false,
            deliveryType: "Frozen Meal",
            image: "https://www.budgetbytes.com/wp-content/uploads/2022/07/Chicken-Alfredo-above.jpg",
        },
        {
            id: 7,
            mealName: "Vegetable Soup",
            description: "Hearty soup with fresh vegetables.",
            calories: 200,
            dairyFree: true,
            nutsFree: true,
            glutenFree: true,
            deliveryType: "Hot Meal",
            image: "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2FPhoto%2FRecipes%2F2024-09-vegetable-soup%2Fvegetable-soup-104",
        },
        {
            id: 8,
            mealName: "Peanut Butter Energy Bowl",
            description: "Oats, peanut butter, and chia seeds.",
            calories: 300,
            dairyFree: true,
            nutsFree: false,
            glutenFree: true,
            deliveryType: "Frozen Meal",
            image: "https://www.noracooks.com/wp-content/uploads/2024/10/PeanutButterEnergyBalls-8.jpg",
        },
        {
            id: 9,
            mealName: "Lentil Curry",
            description: "Lentil curry with basmati rice.",
            calories: 400,
            dairyFree: true,
            nutsFree: true,
            glutenFree: true,
            deliveryType: "Hot Meal",
            image: "https://cookingforpeanuts.com/wp-content/uploads/2021/09/15-Minute-Lentil-Veggie-Curry-1.jpg",
        },
        {
            id: 10,
            mealName: "Salmon Teriyaki",
            description: "Grilled salmon with teriyaki sauce.",
            calories: 520,
            dairyFree: true,
            nutsFree: true,
            glutenFree: true,
            deliveryType: "Frozen Meal",
            image: "https://www.japanesecooking101.com/wp-content/uploads/2023/10/IMG_5965.jpeg",
        },
    ],
}));

export default useWeeklyMealStore;
